/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package entity.view;

/**
 *
 * @author Copini - PC
 */
public class Panel_home extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Home
     */
    public Panel_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_logoSB = new javax.swing.JLabel();
        lb_sideBar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lb_logoSB.setMaximumSize(new java.awt.Dimension(112, 42));
        lb_logoSB.setMinimumSize(new java.awt.Dimension(112, 42));
        lb_logoSB.setPreferredSize(new java.awt.Dimension(112, 42));
        add(lb_logoSB);
        lb_logoSB.setBounds(90, 30, 112, 42);

        lb_sideBar.setBackground(new java.awt.Color(0, 127, 173));
        add(lb_sideBar);
        lb_sideBar.setBounds(0, 0, 300, 1080);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_logoSB;
    private javax.swing.JLabel lb_sideBar;
    // End of variables declaration//GEN-END:variables
}
